# Adminisrator user and password
admin_user: Administrator
admin_password: password1

# ram quota for the cluster
cluster_ram_quota: 512

# bucket and replicas
bucket_name: sample
bucket_ram_quota: 256
num_replicas: 2

couchbase_master_node:
  host: "10.0.2.101"
  port: "8091"
