sysctl_params_dict:
  - { name: vm.swappiness, value: "0" }
  - { name: net.ipv4.ip_forward, value: "0" }
  - { name: net.ipv4.conf.default.rp_filter, value: "1" }
  - { name: net.ipv4.conf.default.accept_source_route, value: "0" }
  - { name: kernel.sysrq, value: "1" }
  - { name: kernel.core_uses_pid, value: "1" }
  - { name: net.ipv4.tcp_syncookies, value: "0" }
  - { name: kernel.msgmnb, value: "65536" }
  - { name: kernel.msgmax, value: "65536" }
  - { name: kernel.shmmax, value: "34359738368" }
  - { name: net.ipv4.tcp_fin_timeout, value: "30" }
  - { name: net.ipv4.tcp_keepalive_time, value: "1800" }
  - { name: net.ipv4.tcp_window_scaling, value: "0" }
  - { name: net.ipv4.tcp_sack, value: "0" }
  - { name: net.ipv4.tcp_timestamps, value: "0" }
